## Site-wide configuration settings. Avoid using _config.yml because that requires a restart when testing locally.",

# Agile in Action logos
logo-large-horizontal: "/assets/agile-in-action-logos/agile-in-action-large-horizontal.png"
logo-favicon: "/assets/agile-in-action-logos/agile-in-action-favicon.ico"

# Allow a workflow process to re-create all guest photos?
wfRecreateGuestImages: false

# Allow a workflow process to re-create all featured images?
wfRecreateFeaturedImages: false

