## Site-wide configuration settings. Avoid using _config.yml because that requires a restart when testing locally.",

# Agile in Action logos
logo-large-horizontal: "/assets/agile-in-action-logos/agile-in-action-large-horizontal.png"
logo-favicon: "/assets/agile-in-action-logos/agile-in-action-favicon.ico"

# Allow a workflow process to re-create all guest photos?
# True generates/regenerates all guest images, overwriting any that might already exist
# False means only generate images for today's date or future dated posts
wfRecreateGuestImages: false

# Allow a workflow process to re-create all featured images?
# True generates/regenerates) all featured images, overwriting any that might already exist
# False means only generate images for today's date or future dated posts
wfRecreateFeaturedImages: true

# This website uses Libsyn to display podcast posts. This is the RSS feed to share with users
rssFeed: "https://feeds.libsyn.com/257606/rss?_ga=2.185818153.1879997348.1668636242-117077834.1667517838"

# Define a default featured image so open graph always has something to display
defaultFeaturedImage: "/assets/agile-in-action-logos/agile-in-action-large-horizontal.png"