on:
  push:
    branches:
      - main # trigger the workflow when changes are pushed on the `main` branch
  schedule:
    - cron: '30 7 * * *' # trigger every day at 00:30
  workflow_dispatch: # trigger workflow manually
name: publish on push and schedule

jobs:

  build:
    name: generate and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # pull the code
        with:
          ref: main # pull from the main branch
      - uses: ./ # run the Dockerfile, which can call entrypoint.sh the assumed filename to start is "Dockerfile" with a capital D
        env:
          USER_SITE_REPOSITORY: BillRaymond/agile-in-action-minima-website #target repo
          GITHUB_TOKEN: ${{ secrets.JEKYLLNEW_PAT }} #personal access token of the source repository
